### PR TITLE
Correct Song Select Level Display Mode

### PR DESCRIPTION
**Pull request by aoki-marika**
Previously levels would always be displayed in GITADORA style, regardless of Skill Mode. This changes it to respect the setting, in line with the song loading screen.

### CODE REVIEW

**Comment by ericpignet** [comment]
Thanks for the contribution and the very tidy code style.

I have a comment. You should display the 'classic' style as well when bCLASSIC譜面判別を有効にする  is true and the song doesn't have any chip on new XG channels.
Like it is done here:
https://github.com/limyz/DTXmaniaNX/blob/master/DTXMania/Code/Stage/07.Performance/DrumsScreen/CActPerfDrumsStatusPanel.cs#L341
or
https://github.com/limyz/DTXmaniaNX/blob/master/DTXMania/Code/Stage/08.Result/CActResultImage.cs#L127
or
https://github.com/limyz/DTXmaniaNX/blob/master/DTXMania/Code/Stage/08.Result/CActResultParameterPanel.cs#L476

And a general recommendation.
If it is a fix (and it seems to be one here), please open an issue, and reference it in the pull request. That helps especially non-developers to keep track of what is being changed/fixed/added in DTXMania NX.

**Comment by aoki-marika** [comment]
My bad re: opening issues, I wasn't sure what the standards for the repository were. I will keep this in mind in the future.

**Comment by ericpignet** [comment]
Thanks for the update!
Sorry just one more comment: does your code support difficulty on 3 digits?
There are quite a few simfiles out there with difficulty as:  #DLEVEL 180
I would expect this to show as 1.80 in XG mode, but I don't think your new code would support it.

Note that normally these simfiles don't have any LEVELDEC (decimal).
For example I recently fixed a bug with the score calculation and used this:
https://github.com/limyz/DTXmaniaNX/blob/master/DTXMania/Code/Score,Song/CScoreIni.cs#L1472

Remark: it would be good in the future to have a centralized code to convert the LEVEL/LEVELDEC into a single level value, which could then be formatted as per class/XG mode.

**Comment by aoki-marika** [comment]
Yes it specifically converts all to 3 digit levels, as noted in the comment, and I was testing on charts with both level formats. `n現在選択中の曲のレベル難易度毎DGB` and `n現在選択中の曲のレベル小数点難易度毎DGB`  already account for these varying situations.

And I agree that it should be centralized, among a ton of other things across the codebase, but this PR was only addressing this specific bug.

**Comment by ericpignet** [comment]
Thanks again for the contribution!

**Pull request merged**
